### ISSUE TITLE
First time AqBanking update complains about unconfigured account

### ISSUE THREAD

**Issue by jgonsior** [johannesgerer/buchhaltung#31]
Hey,
so I've successfully run `buchhaltung setup`. The problems lies in `buchhaltung update`. I get (data truncated and anonymized):

```
[...]
3:2018/02/11 20-56-14:aqbanking(26960):banking.c:  672: Bad IBAN (country code not in upper case)
AqHBCI finished.
Executing Jobs: 3 of 3
Postprocessing jobs
Job Get Transactions: error
Job Get Transactions: error
Job Get Transactions: finished
Resetting provider queues
Executing Jobs: Finished.
buchhaltung: lookupErr: AccountId {aBank = "43060967", aAccount = "MY_ACCOUNT_NUMBER"} not found: Account not configured
CallStack (from HasCallStack):
  error, called at src/Buchhaltung/Commandline.hs:38:11 in main:Buchhaltung.Commandline
```

The relevant part of my config.yml:
```yaml
     aqBanking:                                                                                        
       configDir: aqbanking                                                                            
       connections:                                                                                    
         - user: 'MY_LOGIN_NAME'                                                                 
           blz: '43060967'                                                                         
           url: "https://hbci-pintan.gad.de/cgi-bin/hbciservlet"                                       
           name: 'GLS'                                                                                 
           hbciv: HBCI300                         
           type: PinTan    
```

I've never used ledger before, so my ledger files are totally empty by now. What do I need to enter into them so that the update works?
