### ISSUE TITLE
Use it only for AqBanking auto-import?

### ISSUE THREAD

**Issue by schoettl** [johannesgerer/buchhaltung#38]
Hi Johannes,

I stumbled over this project when I searched for an importer for banking transactions over HBCI.
I've already setup AqBanking, I even have written a rules file to import the downloaded CSV.

But I wonder what's the best way to import it into the ledger journal without getting duplicates.

My best idea is to let AqBanking download transactions

- from the last ledger transaction + 1 day
- to yesterday.

(My bank does not provide `transactionId`s with the transactions.)

Then I would add it to the journal and call `hledger check-dups`.

But how do you solve this problem?

**Comment by johannesgerer** [comment]
Hello Jakob, 
Solving the problem that you describe is one of the intended use cases of  'buchhaltung'. 

See:
https://github.com/johannesgerer/buchhaltung/blob/master/README.md#resolve-duplicates

**Comment by schoettl** [comment]
Thanks Johannes. Does it mean that buchhaltung always downloads *all* transactions and then only adds new transactions to the journal?

I tried to configure buchhaltung but `buchhaltung update` has no effect. It executes quickly without output or errors.

As mentioned, I already configured AqBanking (`aqbanking-cli listaccs` shows my account) and my buchhaltung config is:

```
    ....
    bankAccounts:
       mybank:
           MY_ACC_NUMBER: "assets:bank"
    # does "mybank" must match any other configuration...? and MY_ACC_NUMBER?
    aqBanking:
      configDir: /home/jakob/.aqbanking
      connections: []
```
